-- 0003: 去重功能表（已废弃）
--
-- 去重功能随两级视图一并移除（见 0006 迁移），相关表 categories/packages/dedup 全部删除。
-- 原建表语句引用了 packages 表的外键，packages 删除后无法再 CREATE，故此文件保留为空。
-- 历史 duplicate_groups/duplicate_members/dismissed_pairs 表由 0006 迁移负责 DROP。
--
-- 本文件仅作迁移顺序占位，不执行任何 DDL。
